name: Build and Publish

on: [push, pull_request]

jobs:
  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: â¬ Checkout
        uses: actions/checkout@v4
      - name: ğŸ“¦ Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'latest'
      - name: ğŸ“‚ Installing Dependencies
        run: npm ci
      - name: ğŸ“¦ Building Artifacts
        run: npm run build
      - name: â« Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: production-build
          path: dist/**
  publish-artifacts:
    name: Publish Artifacts
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - name: â¬ Download Artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: production-build
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: dist