name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifacts
    steps:
      - name: â¬ Checkout
        uses: actions/checkout@v4
      - name: ğŸ“¦ Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'latest'
      - name: ğŸ“‚ Installing Dependencies
        run: npm ci
      - name: ğŸ“¦ Building Artifacts
        run: npm run build
      - name: â« Upload Artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: production-build
          path: dist/