name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Artifacts
    steps:
      - name: â¬ Checkout
        uses: actions/checkout@v2.1.1
      - name: ğŸ“¦ Node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: ğŸ“‚ Installing Dependencies
        run: npm ci
      - name: ğŸ“¦ Building Artifacts
        run: npm run build
      - name: â« Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: dist/